# Generated by Django 5.2.8 on 2025-11-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_alter_movie_options_movie_showed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
